name: Deploy to EC2

on:
    workflow_run:
        workflows: [ "MERN CI Pipeline - Build and Push Docker Images" ]
        types:
            - completed

jobs:
    deploy:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-latest
        steps:
            - name: Setup SSH
              run: |
                  mkdir -p ~/.ssh
                  echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa
                  ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

            - name: Deploy to EC2 (Docker Compose)
              run: |+
                  ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
                  set -e

                  echo "Pull Latest Image..."
                  docker image rm ${{ secrets.DOCKER_USERNAME }}/backend:latest || true
                  docker image rm ${{ secrets.DOCKER_USERNAME }}/frontend:latest || true
                  docker pull ${{ secrets.DOCKER_USERNAME }}/backend:latest
                  docker pull ${{ secrets.DOCKER_USERNAME }}/frontend:latest

                  echo "Stop Old Containers..."
                  docker stop backend || true
                  docker rm backend || true
                  docker stop frontend || true
                  docker rm frontend || true

                  echo "Run Backend Container..."
                  docker run -d \
                    --name backend \
                    -p 5000:5000 \
                    ${{ secrets.DOCKER_USERNAME }}/backend:latest

                  echo "Run Frontend Contianer"
                  docker run -d \
                     --name frontend \
                     -p 80:80 \
                     ${{ secrets.DOCKER_USERNAME }}/frontend:latest
                     
                  echo "Running Cointainers..."
                  docker ps

                  echo "Deployment Successfull!"
                  EOF

              #   The below step are used before docker hub 
              #   echo "Moving to project directory..."
              #   cd project/learncicd

              #   echo "Current commit before update...."
              #   git log -1

              #   echo "pulling latest code...."
              #   git fetch origin main
              #   git reset --hard origin/main

              #   echo "Stopping old Docker Containers"
              #   docker compose down || true

              #   echo "Building & Starting Docker Containers..."
              #   docker compose up -d --build

              #   echo "Running Containers..."
              #   docker ps

              #   echo "Deployment Completed...!"
              #   EOF

              #   The below one is used by using pm2
              #   echo "Loading Node via NVM..."
              #   export NVM_DIR="$HOME/.nvm"
              #   [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
              #   nvm use 20 || echo "Node 20 not found"

              #   echo 'Installing backend dependencies...'
              #   cd backend
              #   npm ci

              #   echo "Building Frontend..."
              #   cd ../frontend
              #   npm ci
              #   npm run build

              #   echo "Checking build files..."
              #   ls -lt dist | head

              #   echo "Switching back to backend..."
              #   cd ../backend

              #   echo "Ensuring PM2 is installed..."
              #   command -v pm2 || npm install -g pm2

              #   echo "Restarting app..."
              #   pm2 delete backend || true
              #   pm2 start server.js -i max --name backend
              #   pm2 save
              #   pm2 reload backend

              #   echo "Deployment Completed...!"
              #   EOF




